// =============================================================================
// Code Forge — Session Pool platform on Azure
// Subscription-level deployment: creates RG + spokes per environment
// Generated by hermes-agent · azure-architecture-autopilot skill · Path A
// =============================================================================
targetScope = 'subscription'

@description('Environment short name (dev/stg/prod)')
param env string = 'dev'

@description('Azure region')
param location string = 'westus3'

@description('Project prefix for naming')
param prefix string = 'codeforge'

@description('Object ID of platform admins group (gets RG Owner)')
param adminGroupObjectId string

@description('Tenants for multi-tenant routing')
param tenants array = [ 'tenant-a', 'tenant-b', 'tenant-c' ]

var tags = {
  project: 'code-forge'
  env: env
  managedBy: 'bicep'
  costCenter: 'platform'
}

resource rg 'Microsoft.Resources/resourceGroups@2025-04-01' = {
  name: 'rg-${prefix}-${env}-${location}'
  location: location
  tags: tags
}

module network 'modules/network.bicep' = {
  scope: rg
  name: 'network'
  params: {
    prefix: prefix
    env: env
    location: location
    tags: tags
  }
}

module identity 'modules/identity.bicep' = {
  scope: rg
  name: 'identity'
  params: {
    prefix: prefix
    env: env
    location: location
    tags: tags
  }
}

module storage 'modules/storage.bicep' = {
  scope: rg
  name: 'storage'
  params: {
    prefix: prefix
    env: env
    location: location
    tags: tags
    subnetIdPe: network.outputs.peSubnetId
  }
}

module keyvault 'modules/keyvault.bicep' = {
  scope: rg
  name: 'keyvault'
  params: {
    prefix: prefix
    env: env
    location: location
    tags: tags
    subnetIdPe: network.outputs.peSubnetId
    adminGroupObjectId: adminGroupObjectId
  }
}

module logging 'modules/logging.bicep' = {
  scope: rg
  name: 'logging'
  params: {
    prefix: prefix
    env: env
    location: location
    tags: tags
  }
}

module servicebus 'modules/servicebus.bicep' = {
  scope: rg
  name: 'servicebus'
  params: {
    prefix: prefix
    env: env
    location: location
    tags: tags
    subnetIdPe: network.outputs.peSubnetId
    tenants: tenants
  }
}

module acr 'modules/acr.bicep' = {
  scope: rg
  name: 'acr'
  params: {
    prefix: prefix
    env: env
    location: location
    tags: tags
    subnetIdPe: network.outputs.peSubnetId
  }
}

module aks 'modules/aks.bicep' = {
  scope: rg
  name: 'aks'
  params: {
    prefix: prefix
    env: env
    location: location
    tags: tags
    subnetIdAks: network.outputs.aksSubnetId
    logAnalyticsWorkspaceId: logging.outputs.workspaceId
    acrId: acr.outputs.acrId
    routerIdentityId: identity.outputs.routerIdentityId
    routerIdentityClientId: identity.outputs.routerIdentityClientId
    agentIdentityId: identity.outputs.agentIdentityId
  }
}

module frontdoor 'modules/frontdoor.bicep' = {
  scope: rg
  name: 'frontdoor'
  params: {
    prefix: prefix
    env: env
    tags: tags
    tenants: tenants
    aksFqdn: aks.outputs.controlPlaneFqdn
  }
}

module foundry 'modules/foundry.bicep' = {
  scope: rg
  name: 'foundry'
  params: {
    prefix: prefix
    env: env
    location: location
    tags: tags
    subnetIdPe: network.outputs.peSubnetId
    keyVaultId: keyvault.outputs.kvId
    storageId: storage.outputs.storageId
    logAnalyticsWorkspaceId: logging.outputs.workspaceId
    aksOidcIssuerUrl: aks.outputs.oidcIssuerUrl
    gatewayIdentityId: identity.outputs.gatewayIdentityId
    gatewayIdentityPrincipalId: identity.outputs.gatewayIdentityPrincipalId
  }
}

output rgName string = rg.name
output aksName string = aks.outputs.aksName
output frontDoorEndpoint string = frontdoor.outputs.endpointHostName
output foundryEndpoint string = foundry.outputs.endpoint
output acrLoginServer string = acr.outputs.loginServer
