{{- range $ns := list .Values.namespaces.sessionControl .Values.namespaces.platform .Values.sandboxOrchestrator.sandbox.namespace }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $ns }}
  labels:
    {{- include "code-forge.labels" $ | nindent 4 }}
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
{{- end }}
